# Site settings
title: Code for Resilience 
email: info@codeforresilience.org
description: Partnering local technologists with disaster relief and risk management experts to improve community resilience to natural disasters.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
gems: ['therubyracer', 'jekyll-less']

collections:
  problems:
    output: true
  projects:
    output: true
  cities:
    output: true
